package org.anotherone661.animabeyondhelper.enums;

public enum MOD {
    CIEGO,OSCURAS,POSICIONVENTAJOSA,POSICIONDESVENTAJOSA,BLANCOENMOV,RUIDOSO,SILENCIO,COLORES,CONFUNDIDO,MIEDO,TERROR,LOCURA, DORMIDO, QUEMARROPA
}
